### ISSUE TITLE
Configuration for URI dereferencing

### ISSUE THREAD

**Issue by pwalsh** [openbudgets/platform#2]
# Description

We need an example configuration of using a web server (Apache or NGINX) for URI dereferencing. This was mentioned by @jakubklimek in the last meeting.
# Tasks

Provided by @jakubklimek :
- [x] An example config file
- [x] Any description for how it works/should work
- [x] Any links to examples of where this is deployed

Tasks for @mlukasch:
- [x] Setup for obeu making any changes needed for our particular components.

**Comment by jakubklimek** [comment]
An example from a server with hostname `internal.opendata.cz` running [Apache Jena Fuseki](https://jena.apache.org/documentation/serving_data/) on port `3030`, with data loaded into the `test` dataset - Fuseki can run multiple datasets/databases at once:

Step by step:
We want to get an RDF representation of an entity identified by the IRI `http://internal.opendata.cz/fuseki/test`

`http://localhost:3030/fuseki/query` is the Fuseki SPARQL endpoint, which accepts queries through the `?query` parameter of an HTTP GET request and has the data about `http://internal.opendata.cz/fuseki/test` loaded.

The SPARQL query `DESCRIBE <http://internal.opendata.cz/fuseki/test>` should return some representation of the `http://internal.opendata.cz/fuseki/test` entity as RDF.

The Apache rewrite rule:

```
RewriteRule ^/fuseki/(.*)$ http://localhost:3030/fuseki/query?query=DESCRIBE+<http://internal.opendata.cz/fuseki/$1> [P]
```

ensures, that when someone accesses the IRI `http://internal.opendata.cz/fuseki/test`, which might be an RDF entity, the request gets rewritten into a SPARQL query request:

```
http://localhost:3030/fuseki/query?query=DESCRIBE+<http://internal.opendata.cz/fuseki/test>
```

Note that the rule only applies to IRIs `http://internal.opendata.cz/fuseki/*`, this is because usually, there are other namespaces like `http://internal.opendata.cz/dump/*` for RDF dumps etc. This can of course be customized.

Now for OpenLink Virtuoso, there is a Virtuoso Faceted Browser extension, which also serves as an HTML viewer of the data. Virtuoso by default runs on port `8890` and the extension listens on `/describe/`. Lets say that the entity we want to access now has the IRI `http://ruian.linked.opendata.cz/resource/staty/1`.
On the server with the hostname `ruian.linked.opendata.cz` we have this Apache rewrite rule:

```
RewriteRule ^/resource/(.*)$ http://localhost:8890/describe/?url=http://ruian.linked.opendata.cz/resource/$1 [P]
```

which rewrites the request to:

```
http://localhost:8890/describe/?url=http://ruian.linked.opendata.cz/resource/staty/1
```

and this gives for HTML requests HTML, for RDF requests RDF (using HTTP Content Negotiation).

**Comment by pwalsh** [comment]
Thanks @jakubklimek !

@mlukasch this should be all the info you need to get this setup.

**Comment by schmaluk** [comment]
@jakubklimek @pwalsh Hope that it is solved.
Added this to the nginx.conf (in the master-branch of the integration-repo here on OBEU).
`# 3-store staging:
        location ~ /fuseki/(.+) {
            # resolver needs to be adapted:
            resolver 127.0.0.11;
            proxy_pass http://triple_store_staging:3030/fuseki/query?query=DESCRIBE%20<$scheme://triple_store_staging:3030/fuseki/$1>;
            proxy_set_header        Host $host:$server_port;
            proxy_set_header        X-Real-IP $remote_addr;
            proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header        X-Forwarded-Proto $scheme;
        }`

Have tested it with some dummy data. Not so familiar with rdf. So bit difficult to verify the result. This is what I get from:
curl http://localhost/fuseki/data
`@prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rel:   <http://www.perceive.net/schemas/relationship/> .
@prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> .
@prefix foaf:  <http://xmlns.com/foaf/0.1/> .
`
That gives me the same result as sending the SPARQL-query directly to the fuseki.server via curl http://localhost:33030/fuseki/query?query=DESCRIBE%20%3Chttp%3A%2F%2Flocalhost%3A33030%2Ffuseki%2Fdata%3E

And thanks @jakubklimek for the good explanation.

**Comment by jakubklimek** [comment]
Actually, this would mean that all the URIs (of RDF entities) look like `http://triple_store_staging:3030/fuseki/$1`  because that is passed to the SPARQL query. However, we would like the URIs to be something like `http://data.openbudgets.eu/resource/...` and `http://data.openbudgets.eu/ontology/...`

Testing of URI dereferencing outside of production environment can be a bit challenging due to the fact that the data typically contains the production URIs and therefore they lead to the production server, not to the testing/integration one.

So in my example, in the query part, `DESCRIBE+<http://internal.opendata.cz/fuseki/$1>` queries on the actual server internal.opendata.cz and at the same time all the RDF entities have URIs in a form of `http://internal.opendata.cz/fuseki/...`.

**Comment by schmaluk** [comment]
Since http://eis-openbudgets.iais.fraunhofer.de is our public server for the time being, the following rewrite rules have been added to nginx.conf:
 `location ~ ^/resource/(.+)$ {
    proxy_pass http://triple_store_staging:3030/fuseki/query?query=DESCRIBE%20<http://eis-openbudgets.iais.fraunhofer.de/resource/$1>;
}`

`location ~ ^/ontology/(.+)$ {
    proxy_pass http://triple_store_staging:3030/fuseki/query?query=DESCRIBE%20<http://eis-openbudgets.iais.fraunhofer.de/ontology/$1>;
}`

Can be changed to forward to http://triple_store_production:3030/ if needed.

**Comment by jakubklimek** [comment]
The problem here is that we have no actual data which would use `http://eis-openbudgets.iais.fraunhofer.de/ontology/$1` in its IRIs. We should therefore establish that `http://data.openbudgets.eu` forwards to (for the time being) `http://eis-openbudgets.iais.fraunhofer.de`, update the rewrites and load some actual data to test.

**Comment by pwalsh** [comment]
I can CNAME data.openbudgets.eu to whatever address we need. Maik, please confirm.

**Comment by schmaluk** [comment]
Hi Paul, thanks for the offer. 
Will message you if we Need this. Not sure yet.

**Comment by jakubklimek** [comment]
Yes, this is definitely something we want :-) that is actually the whole point as this is to ensure public access, not only access through ssh tunelling and /etc/hosts.

**Comment by mlukasch** [comment]
Then it would be good, if @pwalsh can Setup CNAME like this: data.openbudgets.eu  = eis-openbudgets.iais.fraunhofer.de

**Comment by schmaluk** [comment]
@pwalsh since it makes sense for @jakubklimek, can you please then set CNAME for:
data.openbudgets.eu = eis-openbudgets.iais.fraunhofer.de 
Thanks

**Comment by pwalsh** [comment]
@mlukasch CNAME is now in place.

**Comment by schmaluk** [comment]
@jakubklimek Will set this task as done hopefully in agreement with you

**Comment by skarampatakis** [comment]
Dereferencing does not seem to be working. 

http://data.openbudgets.eu/ontology/dsd/dimension/fiscalYear

leads to 404, while running the describe query on SPARQL endpoint returns a result.

**Comment by mlukasch** [comment]
The reason why it is not working is, that we have 2 triplestores: Staging & Production. And the URI dereferncing just applies to the production one. But you have used correctly the staging triplestore for your upload Therefore there is a cronjob running hourly which copies the staging triplestore to production. Later this will be replaced by a proper Validation/clearance procedure afaik. Will investigate why the cronjob didnt run.

**Comment by schmaluk** [comment]
@skarampatakis Sorry, have corrected it. It should work by now.

**Comment by skarampatakis** [comment]
Thanks @mlukasch, it works partially. 

But since I requested it through a browser I should get a proper HTML page according to http://wifo5-03.informatik.uni-mannheim.de/bizer/pub/LinkedDataTutorial/

and 

https://www.w3.org/TR/swbp-vocab-pub/

**Comment by schmaluk** [comment]
@skarampatakis Actually what the Sparql-Describe-query returns is not in HTML format. I can return text/plain as Content-Type instead of text/ttl, if Mime-Type in the request is text/html .
And return text/ttl as Content-Type otherwise.

**Comment by schmaluk** [comment]
If you open http://data.openbudgets.eu/ontology/dsd/dimension/fiscalYear now with a browser,  one receives now the result of the Describe-Query as text/plain.
Otherwise one gets the result with the ContentType text/turtle. Hope this meets the above requirements.

**Comment by skarampatakis** [comment]
With a browser the response is recommended to be a proper HTML page.

**Comment by jakubklimek** [comment]
> With a browser the response is recommended to be a proper HTML page.

@skarampatakis Do you have any recommendation about a tool that could generate such page? Since we are using Fuseki and not Virtuoso, we cannot use virtuoso's fct browser for this. So maybe something like pubby?

**Comment by skarampatakis** [comment]
@mlukasch Actually this leads to false statement for semantic web agents, because text/plain is a media type for N-triples. Thus while a browser believes the content is in N-triples it gets Turtle. 

@jakubklimek Pubby is quite "old" I would say. Another option could be [LODView](http://lodview.it/lodview/?IRI=http%3A%2F%2Faemet.linkeddata.es%2Fresource%2FObservation%2Fat_1315943400000_of_0158X_on_HTAMIN1h&sparql=http%3A%2F%2Faemet.linkeddata.es%2Fsparql&prefix=http%3A%2F%2Faemet.linkeddata.es%2Fresource%2F). These solutions are using Java Applet Servers such as Tomcat, which would add an overhead at OBEU Server. 

Another solution would be to use RDFBrowser which we are developing and can be deployed on each server with php enabled, which is the vast majority of commercial used servers. This browser can handle also content negotiation. You can check out this examples. 

http://elina.math.auth.gr/resource/London

or check your IRI using 

http://elina.math.auth.gr/browser?uri=http://dbpedia.org/resource/Prague

OBEU IRIS are currently not working because of the above issue.

**Comment by schmaluk** [comment]
@skarampatakis Sounds great. Do you have maybe a link for your RDFBrowser? I will then install it on our server, if you are ok with it. Alternatively another tomcat for https://github.com/dvcama/LodView would be also ok from my point of view.

**Comment by skarampatakis** [comment]
@mlukasch You can find RDFBrowser on OKGreece Github [repo](https://github.com/okgreece/RDFBrowser). I can help you with deployment and configuration. It has been tested with both apache and nginx.

**Comment by schmaluk** [comment]
@skarampatakis Thanks have found it. Is this urgent from your perspective, otherwise we at Fhg/UniBonn have decided to postpone this until the prototype has been completed.

**Comment by skarampatakis** [comment]
This is not urgent I believe but I think it could be included on the prototype of our platform. I can help you with this if you want. I would suggest to get the pre-built files for easy installation.
