### ISSUE TITLE
FDP to RDF Pipeline as a live component

### ISSUE THREAD

**Issue by pwalsh** [openbudgets/platform#3]
# Description

As part of the live components for WP4, we need an instance of LinkedPipes running with the ob.eu components, that can:
- Take an FDP payload over HTTP from OpenSpending
- Run it through the RDF transformation pipeline
- Write from the pipeline to the staging triple store
- Write the static result (data serialized as RDF) from the pipeline back to the flat file store for that package on OpenSpending
# Tasks
- [ ] Very good mapping for FDP -> RDF pipeline ( @HimmelStein and Marek )
- [x] LinkedPipes can accept a payload via HTTP ( @jakubklimek )
- [x] OpenSpending has a hook that, after a package hits the datastore, it sends it to the pipeline ( @akariv  )
- [x] LinkedPipes outputs result to staging triple store ( Maik with advice from @jakubklimek )
- [x] LinkedPipes outputs file of RDF back to OS Datastore (so requires a way to auth with OS) ( Maik with advice from @jakubklimek )

**Comment by jakubklimek** [comment]
LP-ETL supports HTTP POSTing of data to pipelines since https://github.com/linkedpipes/etl/commit/4807fb53e1234ccb2850b0af41d64a4dc632eb5d

**Comment by pwalsh** [comment]
@HimmelStein are you making progress with the pipeline, in tandem with Marek?

**Comment by HimmelStein** [comment]
Hi @pwalsh, Marek said he will finish the first version, and show us the documentation, then proceed together with some difficult issues. This shall happen in the coming weeks.

**Comment by pwalsh** [comment]
Documentation from Marek: https://docs.google.com/document/d/1TaXsob1R0DRlrEl_k3oAYhZE4cVxnarkmv-rdWbhstc/edit#

**Comment by pwalsh** [comment]
@HimmelStein ( @badmotor ) now that Marek has documented the pipeline, I think it is over to you now to lead on this, on the following angles:
- Work on the mapping of FDP to RDF (as you discussed in plenary)
- Document issues, points for fixing, refactoring and so on
- Run some live tests against the OS datastore (requires @mlukasch to get this pipeline live in the Fraunhofer environ)

If that assessment does not seem right to you, please raise it with myself, Alexandra, and Fabrizio.

**Comment by HimmelStein** [comment]
sure, i work on this.

**Comment by HimmelStein** [comment]
@pwalsh i added comments to all "discussion might be needed (red with yellow background)" parts in the document.

**Comment by schmaluk** [comment]
LinkedPipes outputs to the triplestore now and our server has exposed the endpoint. We need to test the transformation further though with some more test data.
@akariv regarding the hook, have send you the endpoint in a mail, let me know, if something needs to be adpated or discussed. The request to this endpoint should be basically built up as described by Marek: https://github.com/openbudgets/pipeline-fragments/tree/master/FDPtoRDF
@pwalsh @jakubklimek There is this task open: LinkedPipes outputs file of RDF back to OS Datastore (so requires a way to auth with OS) Have not been aware of this before. That means that the transformed RDF OBEU data should also get stored in the OS datastore and not only be stored on our server?

**Comment by HimmelStein** [comment]
@pwalsh  @akariv @jakubklimek @jindrichmynarz @badmotor  we run the curl command using the sample provided by Marek. it works. this means: the FDP2RDF pipleline (at the Fraunhofer server) accepted the sample datapackage.jsonld, transformed the related FDP into RDF, and pushed the results in the Fuseki triple store -- we found them using SPARQL query. To test how well current pipeline works for any FDP2RDF transformation, I uploaded sample csv files to the newest version of the Openspending wizard, followed the steps of the wizard, and have a datapackage.json file, uploaded the csv file into the web, changed the path key in the datapackage.json to the internet address of the csv file, changed the @context key to {"@vocab": "http://test.openbudgets.eu/ontology/fdp#"} (copied from Marek's sample). Then, the same curl command is used to use FDP2RDF pipeline, which returned the same message as the using the sample datapackage.jsonld. But the expected RDFs are found in the Fuseki triple store. 
The two test datapackage.jsonld files are currently uploaded at https://drive.google.com/drive/folders/0Bz4l9o27a9NHTnhMQXFjcldSbUk 
If their formats are correct (please check), we shall move on to the next topic: FDP2RDF for any FDP file.

**Comment by jindrichmynarz** [comment]
Based on a discussion with @pwalsh, the `@context` IRI should be `http://schemas.frictionlessdata.io/fiscal-data-package.jsonld` (see [here](https://github.com/openbudgets/pipeline-fragments/tree/master/FDPtoRDF#input)).

**Comment by HimmelStein** [comment]
@akariv @pwalsh here are some feedback about the OS wizard:
(1) the sample csv which I used is a tiny part of the ESIF-2014 file. This csv file does not have a column for date. a necessary condition to move to Step 3 is: at least one column should be mapped to 'date'. I have to manually add a date column, and repeat the steps again. 
(2) the Date-->Other Date must have the format '%Y-%m-%d', however, it would not accept '2014-01-01'

**Comment by HimmelStein** [comment]
@jindrichmynarz thanks for the quick response. I test again.

**Comment by pwalsh** [comment]
@HimmelStein don't open packager bugs here, they will get lost. Open them on the openspending issue tracker where the team can prioritize.

**Comment by HimmelStein** [comment]
@pwalsh @jindrichmynarz @jakubklimek @mlukasch @badmotor 
current testing results: (1) the FDP2RDF pipeline provided by Marek works along with the attached datapackage.jsonld. (2) it also works, if we change the "path" value, e.g. from "http://protegeserver.cz/" to "http://wenxion.net/pub/". (3) however, if we change the @context value from "http://test.openbudgets.eu/ontology/fdp#" into "http://schemas.frictionlessdata.io/fiscal-data-package.jsonld#", I do not see the expected result -- The pipeline still runs with success. In the final output file, we can also find datapackage name, but no content information. 

The test is based on the datapackage.json, located at https://github.com/openbudgets/pipeline-fragments/blob/master/FDPtoRDF/test/test3/datapackage.jsonld 

I will use the @context in the original datapackage.jsonld ("http://test.openbudgets.eu/ontology/fdp#") file to do other tests.

**Comment by akariv** [comment]
@HimmelStein @jakubklimek @pwalsh @mlukasch 
Please note issue openbudgets/pipeline-fragments#5 - we must have an option to upload the datapackage.json as a URL and not verbatim.

**Comment by HimmelStein** [comment]
@marek-dudas  @pwalsh @jindrichmynarz @jakubklimek @mlukasch @badmotor 
the @context "http://schemas.frictionlessdata.io/fiscal-data-package#" works for the Pipeline version 0.2.5, but not 0.2.3.

**Comment by HimmelStein** [comment]
@akariv the FDP2RDF pipeline has reached to version 0.3.1, and a newer version will come soon. For the new version we would like to test it by sending datapackage.jsonld from http://next.openspending.org/packager/provide-data 
It would be very helpful, if you could realize the test in the coming days.

**Comment by schmaluk** [comment]
Hello, 
I have marked this as done:
- LinkedPipes outputs file of RDF back to OS Datastore (so requires a way to auth with OS) ( Maik with advice from @jakubklimek )
  since we have agreed not to do this in this way in the Meeting from last week but rather store the RDF-files on our Server & expose via http: http://eis-openbudgets.iais.fraunhofer.de/dumps/

**Comment by pwalsh** [comment]
@badmotor I'm closing this. It must be out of date, and any specific issues can be raised with distinct issues, which has been happening over on the pipeline-fragments repo to date.
