### ISSUE TITLE
Work towards beta release of Rudolf

### ISSUE THREAD

**Issue by pwalsh** [openbudgets/platform#4]
# Description

[Rudolf](https://github.com/openbudgets/rudolf) is a Babbage-API-compataible cubes API, running from a triple store over the OpenBudgets.eu data model.

Rudolf is already a working proof of concept by @larjohn but needs assistance from other WP4 partners to bring to a more stable state.

For specific tasks an issues, @larjohn should help define scope, and they can probably be tracked in https://github.com/openbudgets/rudolf/issues 

At a high level though, current tasks look like those below.
# Tasks
- [ ] Track changes to the main Babbage API that OpenSpending implements
- [ ] Consider if anything custom here is able to be ported back to Babbage
- [ ] Any open issues at https://github.com/openbudgets/rudolf/issues 
- [ ] Unit tests
- [ ] Functional tests

**Comment by larjohn** [comment]
A good idea would be to start with the actual babbage tests. I can try converting the test dataset in RDF, using LinkedPipes and then reproduce the original babbage tests in the way Laravel specifies here: https://laravel.com/docs/5.2/testing

**Comment by pwalsh** [comment]
@badmotor @larjohn I'm closing this. It must be out of date, and any specific issues can be raised with distinct issues.
